### ISSUE TITLE
Several instances

### ISSUE THREAD

**Issue by gigi** [Jimdo/prometheus_client_php#106]
Hi!
Help us to deal with metrics for several PHP servers. For example we have three servers with 'some_logical_counter' metric. If we use APCu adapter every counter will be incremented independently. So prometheus should pull and sum three 'some_logical_counters'. If we switch to Redis then three instances share the same value. 
Does package's storage adapter affect the way prometheus should handle data?

**Comment by gdsmith** [comment]
My understanding is that If you are sharing Redis storage between servers/services you should likely include a label to identify the server or use `Redis::setPrefix` to make the adapter behave in the same way as APCu/InMemory.

**Comment by gigi** [comment]
Ok. Thanx
