### ISSUE TITLE
Replace/rewrite InMemory adapter

### ISSUE THREAD

**Issue by bracki** [Jimdo/prometheus_client_php#20]
With #18 we removed all usages of the InMemory adapter.
Either remove it altogether or rewrite it.

**Comment by krukru** [comment]
Any explanation why this got removed? I have some gauges that I don't really need to store in redis/apc, InMemory would be just fine for the job. I just need the RenderTextFormat, which I can't seem to use without a valid redis or apc adapter.

**Comment by bweston92** [comment]
Ok I seem to have just implemented my ReactHTTP server with this package and only just realised that there is no stats because of no code in the in memory adaptor. Any idea on getting this in?

**Comment by krukru** [comment]
I have a pull request that implements the in memory adapter, but I haven't received any feedback on it for a while now.
You can use my fork until we get some comment on the PR

**Comment by bracki** [comment]
Will be fixed by merging #36.

**Comment by bracki** [comment]
Done.
