### ISSUE TITLE
APC(u) store – why not scrapbook?

### ISSUE THREAD

**Issue by tback** [Jimdo/prometheus_client_php#24]
Today I noticed you're working on storing data in APC(u). Did you look at https://github.com/mattiasmullie/scrapbook especially http://www.scrapbook.cash/interfaces/key-value-store/? It's very lightweight. It provides locking primitives, native float increments and lots of other backends.

**Comment by bracki** [comment]
No, haven't been aware of this. From a first glance it seems like a lot of locking is involved in the APC implementation. Thanks for the hint, though.

**Comment by tback** [comment]
I read your implementation. 
Your use of the APCIterator seems quite nice to me and Scrapbook doesn't provide access to the iterator. Closing this.
