### ISSUE TITLE
Php5.5 installed prometheus, encountered apc related issues.

### ISSUE THREAD

**Issue by Wshuhao001** [Jimdo/prometheus_client_php#39]
When I install apcu 5.1.3 extension, add an APCU class to replace the APC class, such as modifying the apc_add to replace apcu_add, but after adding the count by example to get no metrics.

**Comment by andrewhowdencom** [comment]
@Wshuhao001 What was the problem, in the end?

**Comment by Wshuhao001** [comment]
@andrewhowdencom Ok, I installed apcu success in php7, but failed in php5.5, my php5.5 using the Zend Opcache,I do not know if this is the reason.
I made an error when I made make.
![Uploading image.png…]()

**Comment by andrewhowdencom** [comment]
It'd be interesting to see if it happens in PHP 5.6. I think, given PHP 5.5 is EOL, it's unreasonable to expect support for it?

**Comment by Wshuhao001** [comment]
@andrewhowdencom 
Yeah,i have successfully installed in the php5 apcu-4.0.10, but when I run the program, there have been pack and unpack problems, through access, I found that APC does not support these two functions:
```
    /**
     * @param mixed $val
     * @return int
     */
    private function toInteger($val)
    {
        return unpack('Q', pack('d', $val))[1];
    }

    /**
     * @param mixed $val
     * @return int
     */
    private function fromInteger($val)
    {
        return unpack('d', pack('Q', $val))[1];
    }
```
Official display:
5.6.3	The "q", "Q", "J" and "P" codes were added to enable working with 64-bit numbers.
Now I am starting to solve this problem.

**Comment by Wshuhao001** [comment]
I changed this into the view log found no longer error, but no metrics.
```
    /**
     * @param mixed $val
     * @return int
     */
    private function toInteger($val)
    {
        return unpack('L', pack('f', $val))[1];
    }

    /**
     * @param mixed $val
     * @return int
     */
    private function fromInteger($val)
    {
        return unpack('f', pack('L', $val))[1];
    }
```

**Comment by Wshuhao001** [comment]
Well, I succeeded in php5.5.

**Comment by bracki** [comment]
I suppose everything is solved than. But yes, we won't make any efforts to support 5.5.
