### ISSUE TITLE
Exception when sorting gauge values with labels in Redis.php

### ISSUE THREAD

**Issue by crazycodr** [Jimdo/prometheus_client_php#45]
I'm just opening this as a reference to an upcoming PR.

I found an issue that happens when you sort gauge entries with labels. You json_decode the labels and expect them to work with them as an array but json decode produces objects by default. I also have a similar error with the TextFormatRenderer that expects arrays instead of stdclasses.

PR coming soon, by the end of day probably.

**Comment by bracki** [comment]
Merged your changes. Thanks for the contribution!
