### ISSUE TITLE
switch completely to apcu

### ISSUE THREAD

**Issue by bamarni** [Jimdo/prometheus_client_php#47]
I'd like to suggest to solely focus on APCu : 
- Starting from PHP7, APCu moved the bc layer into a separate extension (https://pecl.php.net/package/apcu_bc), personally I'd rather avoid installing it.
- APC was mostly relevant before PHP 5.5, those versions all reached EOL and this library explicitly requires PHP >=5.6 anyway.

WDYT?

**Comment by fesor** [comment]
`APCUIterator` available only since apcu 5.0.0. Which means that in order to have support of apcu we need to drop support for php 5.6.

Maybe it's time to move completely to PHP 7.x?

**Comment by bamarni** [comment]
@bracki : what's your take on this?

**Comment by bracki** [comment]
Closed by #62.
