### ISSUE TITLE
Replace double data type with float data type

### ISSUE THREAD

**Issue by bsacharski** [Jimdo/prometheus_client_php#49]
It looks like the library uses `double` keyword for a phpdoc comments in some places. PHP doesn't really differentiate between `float` and `double` with the former being much more common. IMHO it makes it confusing when reading the code. Additionally, some tools may not handle `double` data type correctly (for instance PHPStan). Therefore I would suggest switching `double` to `float`.

**Comment by bracki** [comment]
According to https://github.com/phpstan/phpstan/issues/214 `double` support landed in PHPStan.
I'd rather keep it as is.
