### ISSUE TITLE
REDIS EXPIRE key

### ISSUE THREAD

**Issue by dinya17** [Jimdo/prometheus_client_php#69]
Can you explain this?

Expose the metrics:
```
$registry = \Prometheus\CollectorRegistry::getDefault();
$renderer = new RenderTextFormat();
$result = $renderer->render($registry->getMetricFamilySamples());
header('Content-type: ' . RenderTextFormat::MIME_TYPE);
echo $result;
```

It means that  every page call will show more and more counters? 
Do i need flush redis after page call?

**Comment by bracki** [comment]
> It means that every page call will show more and more counters?
It means that the counter (or what ever metric you chose) will increase with every call to `inc()`.

> Do i need flush redis after page call?
You never need to flush Redis. In fact I rather recommend using APC.
