### ISSUE TITLE
InMemory Functionality not working

### ISSUE THREAD

**Issue by hpkulkarni** [Jimdo/prometheus_client_php#80]
Hi, I have tried "in-memory" option

It not working at all. Also its not throwing any error. How to fix this.

**Comment by sobi3ch** [comment]
I've tried it through examples and I end up with bumping counter but on `/metric` page I end up with a white page. (?)

**Comment by haiwenzhu** [comment]
Check if you passed param lables with `['labelName' => '$lableValue']`, You can only pass lables with `['labelValue1', 'labelValue2']`, or there will be error occur.

**Comment by gdsmith** [comment]
InMemory will only store the metrics in the memory of the current process, so will not be able to be shared between requests using php-fpm. You would need to either run your own web server using something like [amphp](https://amphp.org/http-server/) or use one of the other Adapters to preserve the metrics across requests.
